In [9]:
import numpy as np

In [10]:
a = np.array([0, 1, 2])
print(type(a))
print(a)
print(a.dtype)

<class 'numpy.ndarray'>
[0 1 2]
int64


In [12]:
f = np.array([100, 200, 300], dtype = np.int16)
print(f)
print(f.dtype)

[100 200 300]
int16


In [13]:
c = np.arange(2, 41, 2)
print(c)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [14]:
#「a 以上 b 以下の数値を c 分割」
d = np.linspace(0, 10, 5)
print(d)

[ 0.   2.5  5.   7.5 10. ]


In [22]:
#「とりあえず指定の要素数をもつ配列だけを用意しておいて、あとから各要素に代入したい」
e2 = np.empty(5)
print(e2)

[ 0.  12.5 25.  37.5 50. ]


In [23]:
f = np.zeros(5)
print(f)

[0. 0. 0. 0. 0.]


In [25]:
f2 = np.ones(5)
print(f2)

[1. 1. 1. 1. 1.]


In [27]:
#0以上1未満のランダムな小数値を初期値とした配列ができあがります
g = np.random.rand(5)
print(g)

[0.37316585 0.0787603  0.15672533 0.59213817 0.46648821]


In [ ]:
#np.array() でリストから配列を作成しますが、配列をリストに変換したいときは tolist() というインスタンスメソッドを利用してください。

In [28]:
a = np.arange(1, 21)
b = a.reshape(4, 5)
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [29]:
#多次元配列から一次元配列を生成するには flatten() か ravel() というインスタンスメソッドを使います。
#latten() は 必ず元の配列が残ります。ravel() は 元の配列が無くなってしまう可能性があります。
d = c.flatten()
print(c)
print(d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [30]:
e = c.ravel()

print(c)
print(e)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [46]:
a = np.arange(1, 101).reshape(10, 10)
print(a)
print(a[0, 0])
print(a[1, 1])
print(a[1:3])
print(a[1:3, 1:3])
print("print(a[1:5:3])")
print(a[1:5:3])
print("print(a[1:5:3, 1:5:3])")
print(a[1:5:3, 1:5:3])
print("print(a[:5, :5])")
print(a[:5, :5])
print("print(a[7:, 7:])")
print(a[7:, 7:])
print("print(a[::3, ::3])")
print(a[::3, ::3])
print("print(a[:, :])")
print(a[:, :])

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
1
12
[[11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[12 13]
 [22 23]]
print(a[1:5:3])
[[11 12 13 14 15 16 17 18 19 20]
 [41 42 43 44 45 46 47 48 49 50]]
print(a[1:5:3, 1:5:3])
[[12 15]
 [42 45]]
print(a[:5, :5])
[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]]
print(a[7:, 7:])
[[ 78  79  80]
 [ 88  89  90]
 [ 98  99 100]]
print(a[::3, ::3])
[[  1   4   7  10]
 [ 31  34  37  40]
 [ 61  64  67  70]
 [ 91  94  97 100]]
print(a[:, :])
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  1

In [48]:
a = np.arange(1, 20)
#a = np.append(a, 20)
a = np.append(a, (21, 22, 23, 24))
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 21 22 23 24]


In [50]:
#特定の場所に追加したいときは np.insert() を使います。
b = np.arange(1, 6)
b = np.insert(b,1,6)
#b = np.insert(b, 3, (7, 8))
print(b)

[1 6 2 3 4 5]


In [52]:
a =  [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
b = [1, 1, 1]

# 上から2行目に1行追加
c = np.insert(a, 2, b, 0)
print(c)

# 左から2列目に1列追加
e = np.insert(a, 2, b, 1)
print(e)

[[0 0 0]
 [0 0 0]
 [1 1 1]
 [0 0 0]]
[[0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]]


In [53]:
#要素の削除には np.delete() を使います。
a = np.arange(5)
a = np.delete(a, 2)
print(a)

[0 1 3 4]


In [54]:
# 1行目を削除
b = np.arange(1, 26).reshape(5, 5)
b = np.delete(b, 1, 0)
print(b)

# 1列目を削除
c = np.arange(1, 26).reshape(5, 5)
c = np.delete(c, 1, 1)
print(c)

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  3  4  5]
 [ 6  8  9 10]
 [11 13 14 15]
 [16 18 19 20]
 [21 23 24 25]]


In [55]:
a = np.arange(1, 11)
print(a)
print(a + 1)
print(a - 1)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  3  4  5  6  7  8  9 10 11]
[0 1 2 3 4 5 6 7 8 9]


In [56]:
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)
print(a)
print(b)
print(b + a)
print(b - a)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 8 10 12]
 [14 16 18]]
[[6 6 6]
 [6 6 6]]


In [57]:
a = np.random.rand(5)
print(a)

a = a * 6 + 1
print(a)

#切り捨ては np.floor()、切り上げは np.ceil()、四捨五入は np.round() を使いましょう。
print(np.array(np.floor(a), dtype=np.int64))
print(np.array(np.ceil(a), dtype=np.int64))
print(np.array(np.round(a), dtype=np.int64))

[0.74809887 0.20906724 0.53316649 0.78879457 0.1122036 ]
[5.48859325 2.25440346 4.19899891 5.73276743 1.67322161]
[5 2 4 5 1]
[6 3 5 6 2]
[5 2 4 6 2]
